language: node_js
node_js: 8
git:
  depth: 1 # to builds faster
branches:
  only:
    - master

before_script: npm run lint
script: npm run build

before_deploy:
  - npm run package
  - cd dist
deploy:
  provider: npm
  email: "duylamphuong@gmail.com"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tag: true
